# Generated by Django 4.1.1 on 2022-09-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tasks',
            field=models.CharField(max_length=200),
        ),
    ]
